---
- name: Install PostgreSQL on Ubuntu or Fedora
  hosts: g1
  become: yes
  tasks:
    - name: Update package lists (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Update package lists (Fedora)
      dnf:
        update_cache: yes
      when: ansible_distribution == "Fedora"
    - name: Install PostgreSQL and contrib packages (Ubuntu)
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - libpq-dev
        state: present
      when: ansible_distribution == "Ubuntu"
    - name: Install PostgreSQL and contrib packages (Fedora)
      dnf:
        name:
          - postgresql-server
          - postgresql-contrib
          - postgresql-devel
        state: present
      when: ansible_distribution == "Fedora"

      # Just added the below ubuntu step; instead of doing both separately
      
    - name: Initialize PostgreSQL database (Ubuntu & Fedora)
      command: postgresql-setup --initdb
      # when: ansible_distribution == "Ubuntu"

      
    # - name: Initialize PostgreSQL database (Fedora)
    #   command: postgresql-setup --initdb
    #   when: ansible_distribution == "Fedora"
      
    - name: Enable and start PostgreSQL service
      systemd:
        name: postgresql
        enabled: yes
        state: started
    - name: Verify PostgreSQL installation
      command: psql --version
      register: postgres_version
    - name: Install Python3, Pip, and Virtual Environment
      package:
        name:
          - python3
          - python3-pip
          - python3-virtualenv
        state: present
...
