---
- name: Install PostgreSQL on Debian or RedHat
  hosts: g1
  become: yes
  tasks:
    - name: Update package lists (Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Update package lists (RedHat)
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"
    - name: Install PostgreSQL and contrib packages (Debian)
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - libpq-dev
        state: present
      when: ansible_os_family == "Debian"
    - name: Install PostgreSQL and contrib packages (RedHat)
      dnf:
        name:
          - postgresql-server
          - postgresql-contrib
          - postgresql-devel
        state: present
      when: ansible_os_family == "RedHat"


# We need to clear the files in data dir before RedHat family can initialize a PostgreDB, Debians are lenient and can still function with existing files and directories.
# 1. Different Default Database Initialization Process
# Fedora/RedHat-based systems: On RedHat-based systems (including Fedora), PostgreSQL uses the postgresql-setup utility to initialize the database. This utility typically expects the data directory (/var/lib/pgsql/data) to be empty when initializing the database for the first time. If there are any remnants from a previous PostgreSQL installation, it will fail with the error you're seeing.

# Ubuntu/Debian-based systems: On Debian-based systems like Ubuntu, PostgreSQL uses the pg_createcluster utility to create and initialize database clusters. This utility is more flexible and can handle pre-existing directories or clusters more gracefully, typically overwriting them or using a different approach.
    - name: Remove old PostgreSQL data directory (if it exists)
      file:
        path: /var/lib/pgsql/data
        state: absent
      become: yes
      when: ansible_os_family == "RedHat"
     
    - name: Initialize PostgreSQL database (RedHat)
      command: postgresql-setup --initdb
      when: ansible_os_family == "RedHat"
      
    - name: Enable and start PostgreSQL service
      systemd:
        name: postgresql
        enabled: yes
        state: started
    - name: Verify PostgreSQL installation
      command: psql --version
      register: postgres_version
    - name: Install Python3, Pip, and Virtual Environment
      package:
        name:
          - python3
          - python3-pip
          - python3-virtualenv
        state: present
...
