---
- name: Install PostgreSQL on Debian or RedHat
  hosts: g1
  become: yes
  tasks:
    - name: Update package lists (Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Update package lists (RedHat)
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"
    - name: Install PostgreSQL and contrib packages (Debian)
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - libpq-dev
        state: present
      when: ansible_os_family == "Debian"
    - name: Install PostgreSQL and contrib packages (RedHat)
      dnf:
        name:
          - postgresql-server
          - postgresql-contrib
          - postgresql-devel
        state: present
      when: ansible_os_family == "RedHat"
      
    - name: Remove old PostgreSQL data directory (if it exists)
      file:
        path: /var/lib/pgsql/data
        state: absent
      become: yes
      when: ansible_os_family == "RedHat"
     
    - name: Initialize PostgreSQL database (RedHat)
      command: postgresql-setup --initdb
      when: ansible_os_family == "RedHat"
      
    - name: Enable and start PostgreSQL service
      systemd:
        name: postgresql
        enabled: yes
        state: started
    - name: Verify PostgreSQL installation
      command: psql --version
      register: postgres_version
    - name: Install Python3, Pip, and Virtual Environment
      package:
        name:
          - python3
          - python3-pip
          - python3-virtualenv
        state: present
...
