- name: Clone GitHub Repository and Rename
  hosts: g1
  become: yes
  vars:
    home_dir: "{{ '/home/ubuntu' if ansible_distribution == 'Ubuntu' else '/home/fedora' if ansible_distribution == "Fedora" else '/home/cloud-user' }}"

  tasks:
    - name: Install Git (Ubuntu)
      apt:
        name: git
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Git (Fedora & Cloud-user)
      dnf:
        name: git
        state: present
      when: ansible_distribution == "Debian"

    - name: Clone the GitHub repository (alpha branch)
      git:
        repo: "https://github.com/DynamicTimzy/Project-6.git"
        dest: "{{ home_dir }}/Project-6"
        clone: yes
        update: yes
        version: alpha

    - name: Rename the cloned repository to project_file
      command: mv "{{ home_dir }}/Project-6" "{{ home_dir }}/project_file"
      args:
        removes: "{{ home_dir }}/Project-6"
        creates: "{{ home_dir }}/project_file"
    - name: Change ownership of the project directory
      command: sudo chown -R ubuntu:ubuntu "{{ home_dir }}/project_file"
      when: ansible_distribution == "Ubuntu"
    - name: Change ownership of the project directory
      command: sudo chown -R fedora:fedora "{{ home_dir }}/project_file"
      when: ansible_distribution == "Fedora"
    - name: Change ownership of the project directory
      command: sudo chown -R cloud-user:cloud-user "{{ home_dir }}/project_file"
      when: ansible_distribution == "Cloud-user"
