- name: Clone GitHub Repository and Rename
  hosts: g1
  become: yes
  vars:
    project_dir: "{{ '/home/ubuntu' if ansible_distribution == 'Ubuntu' else '/home/fedora' }}"

  tasks:
    - name: Install Git (Ubuntu)
      apt:
        name: git
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Git (Fedora)
      dnf:
        name: git
        state: present
      when: ansible_distribution == "Fedora"

    - name: Clone the GitHub repository
      git:
        repo: "https://github.com/DynamicTimzy/Project-6.git"
        dest: "{{ project_dir }}/Project-6"
        clone: yes
        update: yes

    - name: Rename the cloned repository to project_file
      command: mv "{{ project_dir }}/Project-6" "{{ project_dir }}/project_file"
      args:
        removes: "{{ project_dir }}/Project-6"
        creates: "{{ project_dir }}/project_file"
...
