---
- name: Start Flask and Node.js Applications
  hosts: g1
  become: yes
  vars:
    project_dir: "/home/{{ ansible_user_id }}/project_file"

  tasks:
    - name: Ensure Flask directory exists
      file:
        path: "{{ project_dir }}/flask_app/"
        state: directory
        mode: '0755'

    - name: Create a Python virtual environment
      command: python3 -m venv "{{ project_dir }}/flask_app/venv"
      args:
        chdir: "{{ project_dir }}/flask_app/"
      creates: "{{ project_dir }}/flask_app/venv/bin/activate"

    - name: Install Python dependencies in virtual environment
      shell: "{{ project_dir }}/flask_app/venv/bin/pip install -r requirements.txt"
      args:
        chdir: "{{ project_dir }}/flask_app/"
        
    - name: Start Flask app in the background using virtual environment
      shell: "nohup ./venv/bin/python app.py > flask.log 2>&1 &"
      args:
        chdir: "{{ project_dir }}/flask_app/"

    # - name: Start Flask app in the background using virtual environment
    #   shell: "{{ project_dir }}/flask_app/venv/bin/python app.py &"
    #   args:
    #     chdir: "{{ project_dir }}/flask_app/"

    - name: Ensure Node.js directory exists
      file:
        path: "{{ project_dir }}/node_app/"
        state: directory
        mode: '0755'
    
    - name: Install Node.js dependencies
      command: npm install --only=prod --silent --no-progress
      args:
        chdir: "{{ project_dir }}/node_app/"
    
    - name: Start Node.js app in the background
      shell: "nohup node index.js > node_app.log 2>&1 &"
      args:
        chdir: "{{ project_dir }}/node_app/"
